const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const clone=v=>JSON.parse(JSON.stringify(v));
const days=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
const priorityScore={critical:4,high:3,medium:2,low:1};
const priorityLabel={critical:'Crítica',high:'Alta',medium:'Media',low:'Baja'};
const componentLabel={theory:'Teórico',practice:'Práctico / taller',general:'General'};
const kindLabel={class:'Clase / PPT',guide:'Guía',report:'Informe',notes:'Apuntes',exercise:'Ejercicios',exam:'Evaluación anterior'};

const defaultCourses=[
  {id:'calculo',name:'Cálculo y Estadística',short:'Cálculo',code:'C21-89887',color:'#55ddff',components:['theory','practice'],examEvery:4,testEvery:1,reportMode:'none',taskEvery:null,notes:'Teoría y ejercicios. Test semanal; no genera informes.'},
  {id:'desarrollo',name:'Desarrollo Personal',short:'Desarrollo',code:'C21-89889',color:'#6fa8ff',components:['theory','practice'],examEvery:null,testEvery:null,reportMode:'biweekly',taskEvery:1,notes:'Maneja tareas normales e informes según la semana.'},
  {id:'electricidad',name:'Electricidad',short:'Electricidad',code:'C21-89904',color:'#ffca6a',components:['theory','practice'],examEvery:4,testEvery:null,reportMode:'each',taskEvery:null,practiceEvery:2,notes:'Teoría semanal. Práctica quincenal con informe en cada clase.'},
  {id:'mecanica',name:'Mecánica de Taller',short:'Mecánica',code:'C21-89905',color:'#65e6ad',components:['theory','practice'],examEvery:4,testEvery:null,reportMode:'biweekly',taskEvery:null,notes:'Informe de taller cada dos semanas y examen cada cuatro.'},
  {id:'ondas',name:'Ondas y Calor',short:'Ondas y Calor',code:'C21-89906',color:'#f591ff',components:['theory','practice'],examEvery:null,testEvery:null,reportMode:'each',taskEvery:null,notes:'Cada clase práctica genera un informe.'},
  {id:'datos',name:'Procesamiento de Datos',short:'Procesamiento',code:'C21-89907',color:'#ff8c75',components:['theory'],examEvery:null,testEvery:null,reportMode:'none',taskEvery:null,notes:'Curso teórico; frecuencia de evaluación pendiente de confirmar.'},
  {id:'teoe',name:'Técnicas de Expresión Oral y Escrita',short:'TEOE',code:'C21-89892',color:'#ff7fac',components:['theory','practice'],examEvery:null,testEvery:null,reportMode:'biweekly',taskEvery:1,notes:'Maneja tareas normales e informes.'},
  {id:'equipo',name:'Tecnología del Equipo Pesado',short:'Equipo Pesado',code:'C21-89908',color:'#a88cff',components:['theory','practice'],examEvery:null,testEvery:null,reportMode:'each',taskEvery:null,notes:'Cada clase práctica genera un informe.'},
  {id:'tutoria',name:'Tutoría 1',short:'Tutoría',code:'C21-89893',color:'#9aa4bd',components:['theory'],examEvery:null,testEvery:null,reportMode:'none',taskEvery:null,notes:'Curso teórico; sin recurrencias confirmadas.'}
];

const defaultSchedule=[
  {id:'s1',day:1,course:'calculo',component:'theory',start:'11:20',end:'13:50',room:'1608-LIM',cadence:'weekly'},
  {id:'s2',day:2,course:'equipo',component:'theory',start:'08:00',end:'09:40',room:'407-LIM',cadence:'weekly'},
  {id:'s3',day:2,course:'electricidad',component:'practice',start:'09:40',end:'13:00',room:'907-LIM',cadence:'even'},
  {id:'s4',day:2,course:'desarrollo',component:'theory',start:'14:40',end:'15:30',room:'1605-LIM',cadence:'weekly'},
  {id:'s5',day:2,course:'desarrollo',component:'practice',start:'15:30',end:'17:10',room:'1605-LIM',cadence:'weekly'},
  {id:'s6',day:3,course:'electricidad',component:'theory',start:'08:00',end:'09:40',room:'817-LIM',cadence:'weekly'},
  {id:'s7',day:3,course:'calculo',component:'practice',start:'10:30',end:'13:00',room:'817-LIM',cadence:'weekly'},
  {id:'s8',day:3,course:'mecanica',component:'practice',start:'13:50',end:'17:10',room:'808-LIM',cadence:'weekly'},
  {id:'s9',day:4,course:'ondas',component:'theory',start:'08:00',end:'10:30',room:'407-LIM',cadence:'weekly'},
  {id:'s10',day:4,course:'datos',component:'theory',start:'10:30',end:'13:50',room:'1502-LIM',cadence:'weekly'},
  {id:'s11',day:4,course:'tutoria',component:'theory',start:'14:40',end:'15:30',room:'402-LIM',cadence:'weekly'},
  {id:'s12',day:5,course:'teoe',component:'practice',start:'08:00',end:'09:40',room:'408-LIM',cadence:'weekly'},
  {id:'s13',day:5,course:'teoe',component:'theory',start:'09:40',end:'11:20',room:'408-LIM',cadence:'weekly'}
];

const localBank=[
  {course:'electricidad',topic:'Instrumentos',q:'¿Cómo se conecta un voltímetro para medir la tensión de un componente?',options:['En paralelo','En serie','A tierra únicamente','Con el circuito abierto'],answer:0,why:'El voltímetro compara el potencial entre dos terminales, por eso se conecta en paralelo.'},
  {course:'electricidad',topic:'Seguridad',q:'Antes de usar un ohmímetro, el circuito debe estar…',options:['Energizado','Desenergizado','En cortocircuito','A máxima corriente'],answer:1,why:'El ohmímetro emplea su propia fuente; la energía externa puede falsear la lectura o dañarlo.'},
  {course:'electricidad',topic:'Circuitos en serie',q:'En un circuito en serie, ¿qué magnitud es igual en todos los elementos?',options:['Tensión','Potencia','Corriente','Resistencia'],answer:2,why:'Existe una sola trayectoria, así que la corriente es la misma en cada elemento.'},
  {course:'electricidad',topic:'Ley de Ohm',q:'R1=20 Ω y R2=40 Ω están en serie con 180 V. ¿Cuál es la corriente total?',options:['2 A','3 A','4.5 A','9 A'],answer:1,why:'Rt=60 Ω e I=V/R=180/60=3 A.'},
  {course:'calculo',topic:'Geometría analítica',q:'¿Cuál es la pendiente perpendicular a una recta con pendiente 2/3?',options:['2/3','-2/3','3/2','-3/2'],answer:3,why:'La pendiente perpendicular es el recíproco con signo contrario: -3/2.'},
  {course:'mecanica',topic:'Metrología',q:'¿A cuántos milímetros equivale una pulgada?',options:['24.5 mm','25.0 mm','25.4 mm','25.8 mm'],answer:2,why:'La equivalencia exacta es 1 pulgada = 25.4 mm.'},
  {course:'teoe',topic:'Estructura textual',q:'¿Qué es el tema de un texto?',options:['Una oración con verbo','El asunto general desarrollado','La conclusión','Un ejemplo'],answer:1,why:'El tema nombra brevemente el asunto general del texto.'},
  {course:'ondas',topic:'Calorimetría',q:'¿Qué ecuación expresa el calor sensible?',options:['Q=m·c·ΔT','Q=m·L','P=V·I','R=ρL/A'],answer:0,why:'El calor sensible depende de masa, calor específico y variación de temperatura.'}
];

const seed={version:2,courses:clone(defaultCourses),schedule:clone(defaultSchedule),tasks:[],grades:[],mastery:{},sessions:[],chat:[],cycle:{start:'2026-08-17',weeks:16},settings:{name:'Isa',voiceOutput:true,voiceRate:1,apiKey:'',model:'gemini-3.5-flash-lite'}};
let state=loadState();
let activeFilter='all',studyMode='casual',quiz=null,deferredInstall=null,materialBlock='all',pendingFiles=[],reclassifyId=null,viewWeekOffset=0,voiceSession=false,recognition=null,voiceBusy=false;

function loadState(){
  try{
    const raw=JSON.parse(localStorage.getItem('lunar-state')||localStorage.getItem('jarvis-state')||'{}');
    const oldVersion=Number(raw.version||1);
    const merged={...clone(seed),...raw,settings:{...seed.settings,...(raw.settings||{})},cycle:{...seed.cycle,...(raw.cycle||{})}};
    merged.courses=Array.isArray(raw.courses)&&raw.courses.length?raw.courses:clone(defaultCourses);
    merged.schedule=Array.isArray(raw.schedule)&&raw.schedule.length?raw.schedule:clone(defaultSchedule);
    if(oldVersion<2)merged.settings.voiceOutput=true;
    merged.version=2;localStorage.setItem('lunar-state',JSON.stringify(merged));return merged;
  }catch{return clone(seed)}
}
function saveState(render=true){localStorage.setItem('lunar-state',JSON.stringify(state));if(render)renderAll()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function course(id){return state.courses.find(c=>c.id===id)||{id:'other',name:id||'Sin clasificar',short:id||'Sin curso',code:'',color:'#9aa4bd',components:[]}}
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(v){return v?new Date(v):null}
function startOfWeek(d=new Date()){const x=new Date(d);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);x.setHours(0,0,0,0);return x}
function academicWeekAt(d=new Date()){const start=startOfWeek(new Date(`${state.cycle.start}T12:00:00`));const target=startOfWeek(d);return Math.max(1,Math.floor((target-start)/604800000)+1)}
function currentAcademicWeek(){return academicWeekAt(new Date())}
function blockForWeek(w){const start=Math.floor((Math.max(1,w)-1)/4)*4+1;return`${start}-${start+3}`}
function rangeForBlock(v){if(v==='all')return[1,Number(state.cycle.weeks)||16];const [a,b]=v.split('-').map(Number);return[a,b]}
function weekDates(w=currentAcademicWeek()){const start=startOfWeek(new Date(`${state.cycle.start}T12:00:00`));start.setDate(start.getDate()+(w-1)*7);const end=new Date(start);end.setDate(end.getDate()+6);return[start,end]}
function daysUntil(d){if(!d)return 999;const a=new Date();a.setHours(0,0,0,0);const b=new Date(d);b.setHours(0,0,0,0);return Math.round((b-a)/86400000)}
function isToday(d){return d&&dateKey(d)===dateKey()}
function formatDue(v){const d=parseDate(v);if(!d)return'Sin fecha';const n=daysUntil(d),time=d.toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'});if(n===0)return`Hoy · ${time}`;if(n===1)return`Mañana · ${time}`;if(n===-1)return'Ayer';return`${d.toLocaleDateString('es-PE',{day:'numeric',month:'short'})} · ${time}`}
function scheduleMatches(item,w){return item.cadence==='weekly'||!item.cadence||(item.cadence==='odd'&&w%2===1)||(item.cadence==='even'&&w%2===0)}
function sortedTasks(includeDone=false){return state.tasks.filter(t=>includeDone||!t.done).sort((a,b)=>{const ad=a.due?new Date(a.due).getTime():Infinity,bd=b.due?new Date(b.due).getTime():Infinity;return((bd<Date.now())-(ad<Date.now()))||ad-bd||priorityScore[b.priority]-priorityScore[a.priority]})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2700)}

const DB_NAME='jarvis-files',STORE='materials';
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE,{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbAll(){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbPut(v){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).put(v);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
async function dbDelete(id){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}

function setupSelects(){
  const html=state.courses.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');
  ['#taskCourse','#gradeCourse','#studyCourse','#materialCourse','#classCourse'].forEach(s=>{const el=$(s);if(el){const old=el.value;el.innerHTML=html;if([...el.options].some(o=>o.value===old))el.value=old}});
  const filter=$('#materialCourseFilter');if(filter){const old=filter.value;filter.innerHTML=`<option value="all">Todos los cursos</option>${html}`;filter.value=[...filter.options].some(o=>o.value===old)?old:'all'}
}
function renderAll(){setupSelects();renderDashboard();renderCalendar();renderCourses();renderTasks();renderGrades();renderMastery();renderMaterials();updateSettingsUI()}
async function renderDashboard(){
  const now=new Date(),w=currentAcademicWeek(),pending=sortedTasks(),week=pending.filter(t=>{const n=daysUntil(parseDate(t.due));return n>=0&&n<=7}),overdue=pending.filter(t=>t.due&&new Date(t.due)<now);
  $('#todayLabel').textContent=now.toLocaleDateString('es-PE',{weekday:'long',day:'numeric',month:'long'});const h=now.getHours();$('#greeting').textContent=`Buenas ${h<12?'días':h<19?'tardes':'noches'}, ${state.settings.name}.`;
  $('#briefingLine').textContent=overdue.length?`Hay ${overdue.length} pendiente${overdue.length===1?'':'s'} atrasado${overdue.length===1?'':'s'}. Organicemos la recuperación.`:pending.length?`Tienes ${pending.length} actividad${pending.length===1?'':'es'} pendiente${pending.length===1?'':'s'}.`:`Semana ${w} bajo control. No hay entregas registradas.`;
  $('#metricPending').textContent=pending.length;$('#metricWeek').textContent=week.length;$('#academicWeekTitle').textContent=`Semana ${w} de ${state.cycle.weeks}`;$('#cycleBlock').textContent=`Bloque ${blockForWeek(w)}`;const pct=Math.min(100,Math.round(w/Number(state.cycle.weeks)*100));$('#cycleProgressLabel').textContent=`${pct}%`;$('#cycleProgressBar').style.width=`${pct}%`;
  const files=await dbAll().catch(()=>[]);$('#metricFiles').textContent=files.length;
  $('#priorityList').innerHTML=pending.length?pending.slice(0,4).map((t,i)=>`<article class="priority-item"><span class="priority-rank">${String(i+1).padStart(2,'0')}</span><div><h4>${esc(t.title)}</h4><p>${esc(course(t.course).short)} · ${formatDue(t.due)}${t.week?` · semana ${t.week}`:''}</p></div><span class="priority-tag ${t.priority}">${priorityLabel[t.priority]}</span></article>`).join(''):`<div class="empty-inline"><b>Sin pendientes registrados</b>Añade entregas o deja que LUNAR proyecte el ciclo.</div>`;
  renderTodaySchedule();renderForecast();
}
function renderTodaySchedule(){const today=new Date().getDay(),w=currentAcademicWeek(),items=state.schedule.filter(x=>Number(x.day)===today&&scheduleMatches(x,w)).sort((a,b)=>a.start.localeCompare(b.start));const tasks=sortedTasks().filter(t=>isToday(parseDate(t.due))).slice(0,2);const all=[...items.map(x=>({time:x.start,title:course(x.course).short,meta:`${componentLabel[x.component]} · Aula ${x.room||'por confirmar'}`})),...tasks.map(t=>({time:parseDate(t.due)?.toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'})||'Hoy',title:t.title,meta:`Entrega · ${course(t.course).short}`}))].sort((a,b)=>a.time.localeCompare(b.time));$('#todaySchedule').innerHTML=all.length?all.map(x=>`<div class="timeline-item"><time class="timeline-time">${esc(x.time)}</time><span class="timeline-line"></span><div class="timeline-content"><b>${esc(x.title)}</b><span>${esc(x.meta)}</span></div></div>`).join(''):`<div class="empty-inline"><b>Sin clases ni entregas hoy</b>El día está libre en el horario registrado.</div>`}
function nextMultiple(w,n){return w%n===0?w:Math.ceil(w/n)*n}
function forecastEvents(){const w=currentAcademicWeek(),events=[];for(const c of state.courses){if(c.examEvery)events.push({week:nextMultiple(w,Number(c.examEvery)),title:`Examen de ${c.short}`,meta:`Cada ${c.examEvery} semanas`,icon:'EX'});if(c.testEvery)events.push({week:nextMultiple(w,Number(c.testEvery)),title:`Test de ${c.short}`,meta:c.testEvery===1?'Semanal':`Cada ${c.testEvery} semanas`,icon:'TS'});if(c.reportMode==='biweekly')events.push({week:nextMultiple(w,2),title:`Informe de ${c.short}`,meta:'Proyección quincenal',icon:'IN'});if(c.reportMode==='each'){const practice=state.schedule.find(s=>s.course===c.id&&s.component==='practice');let nw=w;if(practice){while(nw<=state.cycle.weeks&&!scheduleMatches(practice,nw))nw++}events.push({week:nw,title:`Informe práctico de ${c.short}`,meta:'Uno por cada práctica',icon:'IN'})}if(c.taskEvery)events.push({week:nextMultiple(w,Number(c.taskEvery)),title:`Tarea de ${c.short}`,meta:c.taskEvery===1?'Semanal':`Cada ${c.taskEvery} semanas`,icon:'TA'})}return events.filter(e=>e.week<=state.cycle.weeks).sort((a,b)=>a.week-b.week||a.title.localeCompare(b.title))}
function renderForecast(){$('#forecastList').innerHTML=forecastEvents().slice(0,5).map(e=>`<article class="forecast-item"><span class="forecast-icon">${e.icon}</span><div><h4>${esc(e.title)}</h4><p>${esc(e.meta)}</p></div><span class="tag">Sem. ${e.week}</span></article>`).join('')||'<div class="empty-inline"><b>Sin reglas automáticas</b>Configura la frecuencia dentro de cada curso.</div>'}

function renderCalendar(){const w=Math.max(1,currentAcademicWeek()+viewWeekOffset),[a,b]=weekDates(w);$('#weekRange').textContent=`${a.toLocaleDateString('es-PE',{day:'numeric',month:'short'})} – ${b.toLocaleDateString('es-PE',{day:'numeric',month:'short',year:'numeric'})}`;$('#weekCycleLabel').textContent=`Semana académica ${w} · Bloque ${blockForWeek(w)}`;$('#scheduleBoard').innerHTML=[1,2,3,4,5].map(day=>{const items=state.schedule.filter(s=>Number(s.day)===day&&scheduleMatches(s,w)).sort((x,y)=>x.start.localeCompare(y.start));return`<section class="day-column"><div class="day-head ${new Date().getDay()===day&&viewWeekOffset===0?'today':''}">${days[day]}</div><div class="class-list">${items.length?items.map(s=>{const c=course(s.course);return`<article class="class-card" style="--course-color:${c.color}"><b>${esc(c.short)}</b><span>${esc(s.start)}–${esc(s.end)} · ${esc(s.room||'Aula por confirmar')}</span><span class="component">${componentLabel[s.component]||s.component}</span></article>`}).join(''):'<div class="empty-inline">Sin clases</div>'}</div></section>`}).join('')}
function courseRules(c){const r=[];if(c.examEvery)r.push(`Examen cada ${c.examEvery} sem.`);if(c.testEvery)r.push(c.testEvery===1?'Test semanal':`Test cada ${c.testEvery} sem.`);if(c.reportMode==='each')r.push('Informe en cada práctica');if(c.reportMode==='biweekly')r.push('Informe cada 2 sem.');if(c.taskEvery)r.push(c.taskEvery===1?'Tareas semanales':`Tarea cada ${c.taskEvery} sem.`);return r.length?r:['Sin recurrencias confirmadas']}
function renderCourses(){$('#courseGrid').innerHTML=state.courses.map(c=>`<article class="course-card" style="--course-color:${c.color}"><div class="course-card-head"><div><h3>${esc(c.name)}</h3><span class="code">${esc(c.code||'Sin código')}</span></div><button class="edit-course" data-edit-course="${esc(c.id)}" aria-label="Editar curso">✎</button></div><div class="component-row">${(c.components||[]).map(x=>`<span class="component-badge">${componentLabel[x]||x}</span>`).join('')}</div><div class="rule-row">${courseRules(c).map(r=>`<span class="rule-chip">${esc(r)}</span>`).join('')}</div>${c.notes?`<p class="course-notes">${esc(c.notes)}</p>`:''}</article>`).join('')}

function renderTasks(){const q=($('#taskSearch')?.value||'').toLowerCase();let list=state.tasks.filter(t=>{const match=activeFilter==='all'||(activeFilter==='done'?t.done:activeFilter==='pending'?!t.done:activeFilter==='reports'?t.type==='Informe':activeFilter==='exams'?t.type==='Examen':true);return match&&`${t.title} ${course(t.course).name}`.toLowerCase().includes(q)}).sort((a,b)=>(a.done-b.done)||((a.due?new Date(a.due):Infinity)-(b.due?new Date(b.due):Infinity)));$('#taskBoard').innerHTML=list.length?list.map(t=>`<article class="task-card ${t.done?'done':''} ${!t.done&&t.due&&new Date(t.due)<new Date()?'overdue':''}"><div class="task-top"><span class="task-type">${esc(t.type)}</span><button class="task-menu" data-delete-task="${t.id}" aria-label="Eliminar">×</button></div><h3>${esc(t.title)}</h3><span class="task-course">${esc(course(t.course).name)}</span><span class="task-detail">${componentLabel[t.component]||'General'}${t.week?` · Semana ${t.week} · Bloque ${blockForWeek(t.week)}`:''}</span><div class="task-meta"><time>${formatDue(t.due)}<br>${t.duration||60} min</time><button class="check-task" data-toggle-task="${t.id}" aria-label="Completar">${t.done?'✓':'○'}</button></div></article>`).join(''):`<div class="panel empty-inline" style="grid-column:1/-1"><b>No hay entregas aquí</b>Registra una actividad o cambia el filtro.</div>`}
function overallAverage(){if(!state.grades.length)return null;const weighted=state.grades.filter(g=>Number(g.weight)>0),weight=weighted.reduce((s,g)=>s+Number(g.weight),0);if(weight)return weighted.reduce((s,g)=>s+Number(g.value)*Number(g.weight),0)/weight;return state.grades.reduce((s,g)=>s+Number(g.value),0)/state.grades.length}
function renderGrades(){const avg=overallAverage();$('#overallAverage').textContent=avg==null?'—':avg.toFixed(2);$('#gradeSummaryText').textContent=avg==null?'Aún no hay notas':state.grades.some(g=>Number(g.weight)>0)?'Promedio ponderado de notas con peso':'Promedio simple';$('#gradeTableWrap').innerHTML=state.grades.length?`<table class="data-table"><thead><tr><th>Curso</th><th>Tipo</th><th>Evaluación</th><th>Semana</th><th>Nota</th><th>Peso</th><th></th></tr></thead><tbody>${state.grades.map(g=>`<tr><td>${esc(course(g.course).short)}</td><td>${esc(g.type||'Evaluación')}</td><td>${esc(g.name)}</td><td>${g.week||'—'}</td><td><strong>${Number(g.value).toFixed(1)}</strong></td><td>${g.weight?`${g.weight}%`:'—'}</td><td><button class="delete-row" data-delete-grade="${g.id}">×</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty-inline"><b>Aún no hay notas</b>Registra tests, exámenes e informes por separado.</div>'}
function renderMastery(){const entries=Object.entries(state.mastery);$('#masteryList').innerHTML=entries.length?entries.slice(0,10).map(([k,m])=>`<div class="mastery-item"><div class="focus-label"><span>${esc(k)}</span><b>${m.level||0}%</b></div><div class="track"><i style="width:${m.level||0}%"></i></div></div>`).join(''):'<div class="empty-inline"><b>Sin diagnóstico todavía</b>Completa entrenamientos para detectar debilidades.</div>'}

async function renderMaterials(){const all=await dbAll().catch(()=>[]),filterCourse=$('#materialCourseFilter')?.value||'all',[a,b]=rangeForBlock(materialBlock);const list=all.filter(f=>(filterCourse==='all'||f.course===filterCourse)&&(materialBlock==='all'||(Number(f.week)>=a&&Number(f.week)<=b)));const bytes=all.reduce((s,f)=>s+Number(f.size||0),0);$('#fileCount').textContent=`${all.length} archivo${all.length===1?'':'s'}`;$('#storageUsed').textContent=`${(bytes/1048576).toFixed(1)} MB usados`;$('#storageBar').style.width=`${Math.min(100,bytes/(500*1048576)*100)}%`;const groups={};for(const f of list){const key=`${f.course||'unclassified'}|${f.week?blockForWeek(Number(f.week)):'Sin semana'}`;(groups[key]??=[]).push(f)}$('#materialFolders').innerHTML=Object.keys(groups).length?Object.entries(groups).sort().map(([key,files])=>{const [cid,block]=key.split('|'),c=course(cid);return`<section class="folder-group"><header class="folder-head"><div><h3>${esc(c.name)}</h3><span>${block==='Sin semana'?'Sin clasificar':`Semanas ${block}`}</span></div><span>${files.length} archivo${files.length===1?'':'s'}</span></header><div class="material-grid">${files.sort((x,y)=>(x.week||99)-(y.week||99)).map(f=>`<article class="material-card"><span class="file-icon">${esc((f.name.split('.').pop()||'FILE').toUpperCase().slice(0,4))}</span><h4>${esc(f.name)}</h4><p>${f.week?`Semana ${f.week}`:'Sin semana'} · ${componentLabel[f.component]||'General'}<br>${kindLabel[f.kind]||'Material'} · ${(Number(f.size||0)/1048576).toFixed(1)} MB</p><div class="material-actions"><button data-download-file="${f.id}">Abrir</button><button data-reclassify-file="${f.id}">Mover</button><button data-delete-file="${f.id}">Eliminar</button></div></article>`).join('')}</div></section>`}).join(''):'<div class="panel empty-inline"><b>No hay archivos en este bloque</b>Sube tus materiales y LUNAR los ordenará por semanas.</div>'}

function switchView(name){$$('[data-view-panel]').forEach(v=>v.classList.toggle('active',v.dataset.viewPanel===name));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const titles={dashboard:'Centro de mando',calendar:'Horario académico',courses:'Cursos y reglas',tasks:'Entregas',study:'Entrenamiento',materials:'Biblioteca académica',grades:'Notas y objetivos',settings:'Ajustes'};$('#viewTitle').textContent=titles[name]||'LUNAR';if(name==='materials')renderMaterials();if(name==='calendar')renderCalendar();window.scrollTo({top:0,behavior:'smooth'})}

function openTaskDialog(){const f=$('#taskForm');f.reset();$('#taskWeek').value=currentAcademicWeek();$('#taskDuration').value=60;const d=new Date(Date.now()+86400000);d.setHours(20,0,0,0);$('#taskDue').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);$('#taskDialog').showModal()}
function saveTask(e){e.preventDefault();const task={id:uid(),title:$('#taskTitle').value.trim(),course:$('#taskCourse').value,component:$('#taskComponent').value,type:$('#taskType').value,week:Number($('#taskWeek').value)||null,due:$('#taskDue').value?new Date($('#taskDue').value).toISOString():'',priority:$('#taskPriority').value,duration:Number($('#taskDuration').value)||60,notes:$('#taskNotes').value.trim(),done:false,createdAt:new Date().toISOString()};if(!task.title)return;state.tasks.push(task);saveState();$('#taskDialog').close();toast('Entrega registrada')}
function openCourseDialog(id=''){const f=$('#courseForm');f.reset();const c=id?course(id):null;$('#courseId').value=c?.id||'';$('#courseDialogTitle').textContent=c?'Editar curso':'Añadir curso';$('#courseName').value=c?.name||'';$('#courseShort').value=c?.short||'';$('#courseCode').value=c?.code||'';$('#courseColor').value=c?.color||'#a88cff';$('#courseTheory').checked=!!c?.components?.includes('theory');$('#coursePractice').checked=!!c?.components?.includes('practice');$('#courseExamEvery').value=c?.examEvery||'';$('#courseTestEvery').value=c?.testEvery||'';$('#courseReportMode').value=c?.reportMode||'none';$('#courseTaskEvery').value=c?.taskEvery||'';$('#courseNotes').value=c?.notes||'';$('#courseDialog').showModal()}
function saveCourse(e){e.preventDefault();const id=$('#courseId').value||$('#courseName').value.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||uid();const value={id,name:$('#courseName').value.trim(),short:$('#courseShort').value.trim(),code:$('#courseCode').value.trim(),color:$('#courseColor').value,components:[...($('#courseTheory').checked?['theory']:[]),...($('#coursePractice').checked?['practice']:[])],examEvery:Number($('#courseExamEvery').value)||null,testEvery:Number($('#courseTestEvery').value)||null,reportMode:$('#courseReportMode').value,taskEvery:Number($('#courseTaskEvery').value)||null,notes:$('#courseNotes').value.trim()};const i=state.courses.findIndex(c=>c.id===id);if(i>=0)state.courses[i]=value;else state.courses.push(value);saveState();$('#courseDialog').close();toast('Reglas del curso guardadas')}
function saveClass(e){e.preventDefault();state.schedule.push({id:uid(),course:$('#classCourse').value,day:Number($('#classDay').value),component:$('#classComponent').value,start:$('#classStart').value,end:$('#classEnd').value,room:$('#classRoom').value.trim(),cadence:$('#classCadence').value});saveState();$('#classDialog').close();toast('Clase añadida al horario')}
function saveGrade(e){e.preventDefault();state.grades.push({id:uid(),course:$('#gradeCourse').value,type:$('#gradeType').value,week:Number($('#gradeWeek').value)||null,name:$('#gradeName').value.trim(),value:Number($('#gradeValue').value),weight:$('#gradeWeight').value?Number($('#gradeWeight').value):null,date:$('#gradeDate').value});saveState();$('#gradeDialog').close();toast('Nota registrada')}

function openMaterialDialog(files=[],existing=null){pendingFiles=files;reclassifyId=existing?.id||null;$('#materialForm').reset();$('#materialCourse').value=existing?.course||state.courses[0].id;$('#materialComponent').value=existing?.component||'theory';$('#materialWeek').value=existing?.week||currentAcademicWeek();$('#materialKind').value=existing?.kind||'class';$('#pendingFilesLabel').textContent=existing?`Moviendo: ${existing.name}`:`${files.length} archivo${files.length===1?'':'s'} seleccionado${files.length===1?'':'s'}: ${files.map(f=>f.name).join(', ')}`;updateBlockPreview();$('#materialDialog').showModal()}
function updateBlockPreview(){const w=Number($('#materialWeek').value)||1;$('#blockPreview').textContent=`Se guardará en Semanas ${blockForWeek(w)} · semana ${w}`}
async function saveMaterials(e){e.preventDefault();const meta={course:$('#materialCourse').value,component:$('#materialComponent').value,week:Number($('#materialWeek').value),kind:$('#materialKind').value};if(reclassifyId){const item=(await dbAll()).find(f=>f.id===reclassifyId);if(item)await dbPut({...item,...meta})}else{for(const file of pendingFiles){if(file.size>30*1048576){toast(`${file.name} supera 30 MB`);continue}await dbPut({id:uid(),name:file.name,type:file.type||'application/octet-stream',size:file.size,addedAt:new Date().toISOString(),blob:file,...meta})}}pendingFiles=[];reclassifyId=null;$('#materialDialog').close();await renderMaterials();renderDashboard();toast('Material clasificado y guardado')}

function briefingText(){const p=sortedTasks(),over=p.filter(t=>t.due&&new Date(t.due)<new Date()),today=p.filter(t=>isToday(parseDate(t.due))),w=currentAcademicWeek(),classes=state.schedule.filter(s=>Number(s.day)===new Date().getDay()&&scheduleMatches(s,w));let text=`Estás en la semana académica ${w}, bloque ${blockForWeek(w)}. `;text+=p.length?`Tienes ${p.length} pendientes. `:'No tienes entregas pendientes registradas. ';if(over.length)text+=`${over.length} están atrasadas. `;if(classes.length)text+=`Hoy tienes ${classes.length} bloques de clase: ${classes.map(s=>course(s.course).short).join(', ')}. `;if(today.length)text+=`También vencen hoy: ${today.map(t=>t.title).join(', ')}. `;if(p[0])text+=`Te recomiendo empezar por ${p[0].title}.`;return text}
function planText(minutes){const tasks=sortedTasks();if(!tasks.length)return'No tengo entregas registradas para distribuir. Añade tus pendientes y volveré a planificar.';let left=minutes,parts=[];for(const t of tasks){if(left<15)break;const use=Math.min(Number(t.duration)||60,Math.max(15,left-(parts.length?10:0)));parts.push(`${use} minutos para ${t.title}`);left-=use+10}return`Plan de ${minutes} minutos: ${parts.join('; ')}.${left>0?` Quedan ${Math.max(0,left)} minutos de margen.`:''}`}
function appendBubble(role,text,persist=true){const el=$('#conversation'),wrap=document.createElement('div');wrap.className=`bubble ${role}`;wrap.innerHTML=`<span>${role==='lunar'?'LUNAR':'ISA'}</span><p>${esc(text).replace(/\n/g,'<br>')}</p>`;el.appendChild(wrap);while(el.children.length>10)el.firstElementChild.remove();el.scrollTop=el.scrollHeight;if(persist){state.chat=state.chat||[];state.chat.push({role,text,date:new Date().toISOString()});state.chat=state.chat.slice(-20);saveState(false)}}
function renderChatHistory(){if(!state.chat?.length)return;const el=$('#conversation');el.innerHTML='';state.chat.slice(-8).forEach(m=>appendBubble(m.role,m.text,false))}
function setVoiceStatus(text,stateName=''){const cap=$('#voiceCaption');cap.textContent=text;$('#voiceCore').classList.toggle('active',stateName==='listening');$('#voiceCore').classList.toggle('speaking',stateName==='speaking');$('#voiceBtn').classList.toggle('active',stateName==='listening')}
function speak(text){return new Promise(resolve=>{if(!('speechSynthesis'in window)||!state.settings.voiceOutput){resolve();return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/[*#_`]/g,''));u.lang='es-PE';u.rate=Number(state.settings.voiceRate)||1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/es-(PE|MX|ES)/i.test(v.lang))||voices.find(v=>v.lang.startsWith('es'))||null;u.onstart=()=>setVoiceStatus('LUNAR está respondiendo…','speaking');u.onend=()=>{setVoiceStatus(voiceSession?'Continuando conversación…':'Toca para hablar');resolve()};u.onerror=()=>resolve();speechSynthesis.speak(u)})}
async function respond(text,fromVoice=false){appendBubble('lunar',text);if(fromVoice||state.settings.voiceOutput)await speak(text)}
function findCourseIn(text){const low=text.toLowerCase();return state.courses.find(c=>low.includes(c.name.toLowerCase())||low.includes(c.short.toLowerCase()))}
async function handleCommand(raw,fromVoice=false){const cmd=raw.trim();if(!cmd)return;appendBubble('user',cmd);const low=cmd.toLowerCase();let response='';
  if(/qué tengo|que tengo|briefing|\bestado\b/.test(low))response=briefingText();
  else{const hours=low.match(/tengo\s+(\d+(?:[.,]\d+)?)\s*(hora|horas|minuto|minutos)/);if(hours){const n=Number(hours[1].replace(',','.'));response=planText(hours[2].startsWith('hora')?Math.round(n*60):Math.round(n))}}
  if(!response&&/preguntas|pregúntame|preguntame|modo examen|simulacro/.test(low)){const c=findCourseIn(low);if(c)$('#studyCourse').value=c.id;const range=low.match(/semanas?\s*(\d+)\s*(?:a|al|-)\s*(\d+)/);if(range)$('#studyBlock').value=`${range[1]}-${range[2]}`;studyMode=/examen|simulacro/.test(low)?'exam':'casual';$$('.mode-card').forEach(b=>b.classList.toggle('selected',b.dataset.mode===studyMode));switchView('study');response=`He preparado ${studyMode==='exam'?'un simulacro':'un entrenamiento'} de ${course($('#studyCourse').value).name}, usando el bloque ${$('#studyBlock').value==='all'?'completo':`de semanas ${$('#studyBlock').value}`}. Pulsa iniciar cuando estés lista.`}
  if(!response&&/estoy atrasada|no hice nada|auxilio/.test(low)){const p=sortedTasks();response=p.length?`Modo rescate activado. Primero trabaja 15 minutos en ${p[0].title}. Después descansa 5 minutos y continúa con ${p[1]?.title||'la misma actividad'}.`:'Modo rescate activado. Dime qué debes entregar y lo convertiré en un plan corto.'}
  if(!response){const grade=low.match(/registra\s+(\d+(?:[.,]\d+)?)\s+en\s+(.+)/);if(grade){const c=findCourseIn(grade[2]);if(c)$('#gradeCourse').value=c.id;$('#gradeValue').value=grade[1].replace(',','.');$('#gradeWeek').value=currentAcademicWeek();$('#gradeDate').value=dateKey();$('#gradeDialog').showModal();response='Abrí el registro de nota. Solo falta indicar el nombre de la evaluación.'}}
  if(!response&&/dónde.*(subo|cargo)|archivos|materiales|biblioteca/.test(low)){const files=await dbAll().catch(()=>[]);response=files.length?`Tienes ${files.length} archivos guardados. Entra a Biblioteca, pulsa Subir materiales y clasifica cada archivo por curso, componente y semana. Así podré reunir automáticamente las semanas 1 a 4, 5 a 8 y los demás bloques.`:'Entra a Biblioteca y pulsa Subir materiales. Te pediré curso, teoría o práctica y número de semana antes de guardar cada archivo.'}
  if(!response&&state.settings.apiKey){appendBubble('lunar','Analizando tus datos y materiales…',false);try{response=await askAI(cmd,false,{})}catch(err){response=`No pude conectar con la inteligencia externa: ${err.message}. La organización local sigue funcionando.`}}
  if(!response)response='Puedo organizar tus entregas, decirte qué toca hoy, distribuir tu tiempo o iniciar un examen por semanas. Para preguntas académicas abiertas, conecta Gemini en Ajustes.';
  await respond(response,fromVoice);return response
}

function initRecognition(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return null;const r=new R();r.lang='es-PE';r.interimResults=false;r.continuous=false;r.maxAlternatives=1;r.onstart=()=>setVoiceStatus('Escuchando…','listening');r.onerror=e=>{voiceBusy=false;if(e.error==='not-allowed'){voiceSession=false;setVoiceStatus('Permite el micrófono para hablar');toast('El navegador bloqueó el micrófono')}else setVoiceStatus('No pude escucharte. Toca otra vez.')};r.onresult=async e=>{voiceBusy=true;const text=e.results[0][0].transcript;$('#commandInput').value=text;setVoiceStatus('Procesando…');await handleCommand(text,true);voiceBusy=false;if(voiceSession)setTimeout(startListening,450)};r.onend=()=>{if(!voiceBusy&&!voiceSession)setVoiceStatus('Toca para hablar')};return r}
function startListening(){if(!recognition)recognition=initRecognition();if(!recognition){toast('La conversación por voz necesita Chrome o Edge');setVoiceStatus('Voz no disponible en este navegador');return}try{recognition.start()}catch{}}
function toggleVoiceSession(){voiceSession=!voiceSession;if(voiceSession){state.settings.voiceOutput=true;saveState(false);$$('[data-console-mode]').forEach(b=>b.classList.toggle('active',b.dataset.consoleMode==='voice'));startListening()}else{try{recognition?.stop()}catch{}speechSynthesis?.cancel();setVoiceStatus('Toca para hablar');$$('[data-console-mode]').forEach(b=>b.classList.toggle('active',b.dataset.consoleMode==='chat'))}}

async function fileToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
function aiReadable(f){return f.type==='application/pdf'||f.type?.startsWith('text/')||f.type?.startsWith('image/')}
function contextText(){return JSON.stringify({academicWeek:currentAcademicWeek(),cycle:state.cycle,courses:state.courses.map(c=>({name:c.name,code:c.code,components:c.components,rules:courseRules(c)})),tasks:state.tasks.map(t=>({title:t.title,course:course(t.course).name,type:t.type,week:t.week,due:t.due,done:t.done})),grades:state.grades.map(g=>({...g,course:course(g.course).name})),mastery:state.mastery,recentConversation:(state.chat||[]).slice(-8)})}
async function askAI(prompt,json=false,opts={}){const key=state.settings.apiKey.trim();if(!key)throw new Error('Falta configurar la clave de Gemini.');const system=`Eres LUNAR, asistente académico personal de Isa, estudiante de Gestión y Mantenimiento de Maquinaria Pesada en TECSUP. Eres serena, directa y rigurosa. Nunca inventes fechas, reglas o contenido de archivos. Prioriza los materiales de Isa y distingue conocimiento complementario. Datos actuales: ${contextText()}`;const parts=[{text:prompt}];if(opts.course){const [a,b]=rangeForBlock(opts.block||'all'),files=(await dbAll()).filter(f=>f.course===opts.course&&Number(f.week)>=a&&Number(f.week)<=b&&(opts.component==='all'||!opts.component||f.component===opts.component)&&aiReadable(f));let total=0;for(const f of files){if(total+f.size>12*1048576||parts.length>5)break;parts.push({inlineData:{mimeType:f.type,data:await fileToBase64(f.blob)}});total+=f.size}parts[0].text+=`\nArchivos adjuntos utilizables: ${parts.length-1}. Si no hay adjuntos, dilo claramente.`}const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(state.settings.model||'gemini-3.5-flash-lite')}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts}],generationConfig:{temperature:.4,maxOutputTokens:4096,...(json?{responseMimeType:'application/json'}:{})}})});const data=await res.json();if(!res.ok)throw new Error(data.error?.message||`Error ${res.status}`);return data.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||''}
async function generateQuestions(courseId,topic,count,block,component){const prompt=`Genera ${count} preguntas para ${course(courseId).name}, semanas ${block==='all'?'1 a '+state.cycle.weeks:block}, componente ${componentLabel[component]||'teoría y práctica'}${topic?`, tema ${topic}`:''}. Basa las preguntas primero en los archivos adjuntos. Devuelve SOLO un arreglo JSON: {"topic":"tema","q":"pregunta","options":["A","B","C","D"],"answer":0,"why":"explicación breve"}. Nivel TECSUP, sin ambigüedades.`;const raw=await askAI(prompt,true,{course:courseId,block,component});const parsed=JSON.parse(raw.replace(/^```json\s*|\s*```$/g,''));if(!Array.isArray(parsed)||!parsed.length)throw new Error('No se generaron preguntas válidas');return parsed.map(q=>({...q,course:courseId}))}
async function startStudy(){const courseId=$('#studyCourse').value,block=$('#studyBlock').value,component=$('#studyComponent').value,topic=$('#studyTopic').value.trim(),count=Math.max(3,Math.min(40,Number($('#questionCount').value)||10));$('#quizStage').innerHTML='<div class="empty-state"><div class="empty-glyph">◐</div><h3>Analizando el bloque…</h3><p>Seleccionando archivos del curso y semanas indicadas.</p></div>';let questions=[];if(state.settings.apiKey){try{questions=await generateQuestions(courseId,topic,count,block,component)}catch(err){toast(`Usaré el banco local: ${err.message}`)}}if(!questions.length){questions=localBank.filter(q=>q.course===courseId&&(topic?`${q.topic} ${q.q}`.toLowerCase().includes(topic.toLowerCase()):true));if(!questions.length){$('#quizStage').innerHTML='<div class="empty-state"><div class="empty-glyph">!</div><h3>Falta material analizable</h3><p>Sube PDFs o conecta Gemini. Los PPT y Word se almacenan, pero conviene exportarlos a PDF para analizarlos.</p></div>';return}questions=questions.slice(0,Math.min(count,questions.length))}quiz={questions,idx:0,score:0,answered:false,answers:[],mode:studyMode,course:courseId,block};renderQuestion()}
function renderQuestion(){const q=quiz.questions[quiz.idx],pct=Math.round(quiz.idx/quiz.questions.length*100);$('#quizStage').innerHTML=`<div class="quiz-box"><div class="quiz-progress"><span>${quiz.mode==='exam'?'SIMULACRO':'ENTRENAMIENTO'} · ${esc(course(quiz.course).short)} · Sem. ${esc(quiz.block)}</span><b>${quiz.idx+1}/${quiz.questions.length}</b></div><div class="track" style="margin-top:9px"><i style="width:${pct}%"></i></div><p class="quiz-question">${esc(q.q)}</p><div class="quiz-options">${q.options.map((o,i)=>`<button class="quiz-option" data-answer="${i}"><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</button>`).join('')}</div><div id="feedbackSlot"></div><div class="quiz-actions"><button class="secondary-button" id="stopQuizBtn">Terminar</button><button class="primary-button" id="nextQuestionBtn" hidden>${quiz.idx===quiz.questions.length-1?'Ver resultado':'Siguiente'}</button></div></div>`}
function answerQuestion(index){if(quiz.answered)return;quiz.answered=true;const q=quiz.questions[quiz.idx],ok=index===Number(q.answer);if(ok)quiz.score++;quiz.answers.push({topic:q.topic,ok});$$('.quiz-option').forEach((b,i)=>{b.disabled=true;if(i===Number(q.answer))b.classList.add('correct');else if(i===index)b.classList.add('wrong')});$('#feedbackSlot').innerHTML=quiz.mode==='exam'?`<div class="feedback ${ok?'good':'bad'}">Respuesta registrada.</div>`:`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'Correcto.':'Aún no.'}</b><br>${esc(q.why)}</div>`;$('#nextQuestionBtn').hidden=false;updateMastery(q.topic,ok)}
function updateMastery(topic,ok){const k=topic||'General',m=state.mastery[k]||{level:0,correct:0,total:0};m.total++;if(ok)m.correct++;m.level=Math.round(m.correct/m.total*100);state.mastery[k]=m;saveState(false);renderMastery()}
function nextQuestion(){if(quiz.idx>=quiz.questions.length-1){finishQuiz();return}quiz.idx++;quiz.answered=false;renderQuestion()}
function finishQuiz(){if(!quiz)return;const pct=Math.round(quiz.score/quiz.questions.length*100),weak=[...new Set(quiz.answers.filter(a=>!a.ok).map(a=>a.topic))];state.sessions.push({id:uid(),date:new Date().toISOString(),course:quiz.course,block:quiz.block,score:quiz.score,total:quiz.questions.length,weak});saveState(false);$('#quizStage').innerHTML=`<div class="empty-state"><div class="empty-glyph">${pct>=70?'✓':'↻'}</div><h3>${pct>=80?'Bloque dominado':pct>=60?'Buen avance':'Necesitamos reforzar'}</h3><p>Resultado: <b>${quiz.score}/${quiz.questions.length}</b> · ${pct}%</p>${weak.length?`<p>Debilidades: ${weak.map(esc).join(', ')}.</p>`:'<p>No se detectaron errores en esta sesión.</p>'}<button class="primary-button" id="retryQuizBtn">Entrenar otra vez</button></div>`;quiz=null;renderMastery()}

function updateSettingsUI(){if(document.activeElement!==$('#apiKey'))$('#apiKey').value=state.settings.apiKey||'';if(document.activeElement!==$('#aiModel'))$('#aiModel').value=state.settings.model||'gemini-3.5-flash-lite';$('#voiceOutput').checked=!!state.settings.voiceOutput;$('#voiceRate').value=state.settings.voiceRate||1;$('#cycleStart').value=state.cycle.start;$('#cycleWeeks').value=state.cycle.weeks;$('#aiModeNote').textContent=state.settings.apiKey?'LUNAR analizará los PDFs e imágenes del bloque elegido.':'Sin Gemini usaré el banco local. Conecta la IA para analizar tus propios archivos.'}
async function testAI(){state.settings.apiKey=$('#apiKey').value.trim();state.settings.model=$('#aiModel').value.trim()||'gemini-3.5-flash-lite';saveState(false);$('#aiStatus').textContent='Comprobando…';try{$('#aiStatus').textContent=await askAI('Responde únicamente: LUNAR en línea.',false,{})||'Conexión correcta';toast('Inteligencia conectada')}catch(err){$('#aiStatus').textContent=err.message}}
function exportBackup(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`lunar-isa-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Respaldo descargado')}
async function importBackup(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.tasks)||!Array.isArray(data.grades))throw new Error('Respaldo no válido');state={...clone(seed),...data,settings:{...seed.settings,...data.settings},cycle:{...seed.cycle,...data.cycle}};saveState();toast('Respaldo restaurado')}catch(err){toast(err.message)}}

function bindEvents(){
  $$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
  $('#quickAddBtn').onclick=openTaskDialog;$('#taskForm').onsubmit=saveTask;$('#addCourseBtn').onclick=()=>openCourseDialog();$('#courseForm').onsubmit=saveCourse;$('#addClassBtn').onclick=()=>{$('#classForm').reset();$('#classStart').value='08:00';$('#classEnd').value='09:40';$('#classDialog').showModal()};$('#classForm').onsubmit=saveClass;
  $('#addGradeBtn').onclick=()=>{$('#gradeForm').reset();$('#gradeWeek').value=currentAcademicWeek();$('#gradeDate').value=dateKey();$('#gradeDialog').showModal()};$('#gradeForm').onsubmit=saveGrade;
  $$('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});$('#taskSearch').oninput=renderTasks;
  $('#prevWeekBtn').onclick=()=>{viewWeekOffset--;renderCalendar()};$('#nextWeekBtn').onclick=()=>{viewWeekOffset++;renderCalendar()};
  $('#commandForm').onsubmit=async e=>{e.preventDefault();const v=$('#commandInput').value;$('#commandInput').value='';await handleCommand(v,false)};$$('[data-command]').forEach(b=>b.onclick=()=>handleCommand(b.dataset.command,false));$('#voiceCore').onclick=toggleVoiceSession;$('#voiceBtn').onclick=()=>{if(!voiceSession)voiceSession=true;startListening()};$$('[data-console-mode]').forEach(b=>b.onclick=()=>{if(b.dataset.consoleMode==='voice'&&!voiceSession)toggleVoiceSession();if(b.dataset.consoleMode==='chat'&&voiceSession)toggleVoiceSession()});
  $$('.mode-card').forEach(b=>b.onclick=()=>{studyMode=b.dataset.mode;$$('.mode-card').forEach(x=>x.classList.toggle('selected',x===b))});$('#startStudyBtn').onclick=startStudy;
  $('#uploadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const files=[...e.target.files];e.target.value='';if(files.length)openMaterialDialog(files)};$('#materialForm').onsubmit=saveMaterials;$('#materialWeek').oninput=updateBlockPreview;$('#materialCourseFilter').onchange=renderMaterials;$$('#blockTabs button').forEach(b=>b.onclick=()=>{materialBlock=b.dataset.block;$$('#blockTabs button').forEach(x=>x.classList.toggle('active',x===b));renderMaterials()});
  $('#saveAiBtn').onclick=testAI;$('#voiceOutput').onchange=e=>{state.settings.voiceOutput=e.target.checked;saveState(false)};$('#voiceRate').oninput=e=>{state.settings.voiceRate=Number(e.target.value);saveState(false)};$('#testVoiceBtn').onclick=()=>speak('Hola, Isa. Soy LUNAR. El sistema académico está en línea.');$('#saveCycleBtn').onclick=()=>{state.cycle.start=$('#cycleStart').value;state.cycle.weeks=Number($('#cycleWeeks').value)||16;saveState();toast('Ciclo actualizado')};$('#exportBtn').onclick=exportBackup;$('#importBtn').onclick=()=>$('#importInput').click();$('#importInput').onchange=e=>{if(e.target.files[0])importBackup(e.target.files[0])};
  $('#calculateTargetBtn').onclick=()=>{const a=Number($('#currentAvg').value),w=Number($('#currentWeight').value),t=Number($('#targetAvg').value);if([a,w,t].some(Number.isNaN)||w<0||w>=100){$('#targetResult').textContent='Completa los tres datos correctamente.';return}const need=(t-a*w/100)/(1-w/100);$('#targetResult').textContent=need>20?`Necesitarías ${need.toFixed(2)}: la meta no es posible con el peso restante.`:need<0?'La meta ya está asegurada.':`Necesitas ${need.toFixed(2)} en el ${100-w}% restante.`};
  document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-course]');if(edit){openCourseDialog(edit.dataset.editCourse);return}const toggle=e.target.closest('[data-toggle-task]');if(toggle){const t=state.tasks.find(x=>x.id===toggle.dataset.toggleTask);if(t)t.done=!t.done;saveState();return}const del=e.target.closest('[data-delete-task]');if(del&&confirm('¿Eliminar esta entrega?')){state.tasks=state.tasks.filter(x=>x.id!==del.dataset.deleteTask);saveState();return}const gd=e.target.closest('[data-delete-grade]');if(gd&&confirm('¿Eliminar esta nota?')){state.grades=state.grades.filter(x=>x.id!==gd.dataset.deleteGrade);saveState();return}const ans=e.target.closest('[data-answer]');if(ans)answerQuestion(Number(ans.dataset.answer));if(e.target.id==='nextQuestionBtn')nextQuestion();if(e.target.id==='stopQuizBtn')finishQuiz();if(e.target.id==='retryQuizBtn')startStudy();const down=e.target.closest('[data-download-file]');if(down){const f=(await dbAll()).find(x=>x.id===down.dataset.downloadFile);if(f){const a=document.createElement('a');a.href=URL.createObjectURL(f.blob);a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}}const move=e.target.closest('[data-reclassify-file]');if(move){const f=(await dbAll()).find(x=>x.id===move.dataset.reclassifyFile);if(f)openMaterialDialog([],f)}const fd=e.target.closest('[data-delete-file]');if(fd&&confirm('¿Eliminar este archivo del dispositivo?')){await dbDelete(fd.dataset.deleteFile);renderMaterials();renderDashboard()}});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true}};
}

function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const add=t=>{try{Promise.resolve(ctx.registerTool(t)).catch(()=>{})}catch{}};add({name:'read_lunar_status',title:'Leer estado de LUNAR',description:'Devuelve semana académica, pendientes y próximas recurrencias.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return{academic_week:currentAcademicWeek(),block:blockForWeek(currentAcademicWeek()),pending:sortedTasks().slice(0,10),forecast:forecastEvents().slice(0,10)}}});add({name:'create_academic_task',title:'Crear entrega',description:'Registra una entrega en LUNAR.',inputSchema:{type:'object',properties:{title:{type:'string'},course_id:{type:'string'},type:{type:'string'},week:{type:'integer'},due:{type:'string'}},required:['title','course_id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(i){if(!i?.title||!state.courses.some(c=>c.id===i.course_id))throw new Error('Datos inválidos');const t={id:uid(),title:i.title,course:i.course_id,type:i.type||'Tarea',week:i.week||currentAcademicWeek(),due:i.due?new Date(i.due).toISOString():'',priority:'medium',duration:60,done:false,component:'theory',notes:'',createdAt:new Date().toISOString()};state.tasks.push(t);saveState();return{id:t.id,status:'created'}}})}

async function init(){setupSelects();bindEvents();renderAll();renderChatHistory();registerWebMCP();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setTimeout(()=>{$('#boot').remove();$('#app').hidden=false},420)}
init();
